version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./site/Dockerfile
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    ports :
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini

  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: esgi
      POSTGRES_USER: esgi
      POSTGRES_PASSWORD: Test1234

  mail:
    image: namshi/smtp
    environment:
      - MAIL_USER=user
      - MAIL_PASS=pass
    ports:
      - "25:25"